FROM alpine:3.19

ARG DAPPER_HOST_ARCH
ENV ARCH=${DAPPER_HOST_ARCH}

RUN apk update && apk add ca-certificates curl bash git jq docker

ENV DAPPER_ENV REPO OS ARCH TAG DRONE_TAG LOCAL_ARTIFACTS DOCKER_USERNAME DOCKER_PASSWORD
ENV DAPPER_SOURCE /go/src/github.com/rancher/system-agent-installer-k3s/
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["build"]
