FROM debian:buster-20220801

ARG DAPPER_HOST_ARCH
ENV ARCH=${DAPPER_HOST_ARCH}

RUN apt-get install -y apt-transport-https ca-certificates gnupg wget curl

RUN wget -O - https://download.docker.com/linux/debian/gpg | apt-key add - && \
    echo "deb [arch=${ARCH}] https://download.docker.com/linux/debian buster stable" >> /etc/apt/sources.list && \
    cat /etc/apt/sources.list

RUN apt-get install -y bash git jq

RUN if [ "${ARCH}" = "s390x" ]; then \
        curl -L https://download.docker.com/linux/static/stable/s390x/docker-18.06.3-ce.tgz | tar xzvf - && \
        cp docker/docker /usr/bin/ && \
        chmod +x /usr/bin/docker; \
    elif [ "${ARCH}" = "arm" ]; then \
        curl -L https://download.docker.com/linux/static/stable/armhf/docker-18.06.3-ce.tgz | tar xzvf - && \
        cp docker/docker /usr/bin/ && \
        chmod +x /usr/bin/docker; \
    else \
        apt-get install -y docker-ce; \
    fi

ENV DAPPER_ENV REPO OS ARCH TAG DRONE_TAG LOCAL_ARTIFACTS DOCKER_USERNAME DOCKER_PASSWORD
ENV DAPPER_SOURCE /go/src/github.com/rancher/system-agent-installer-k3s/
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["build"]
