#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p artifacts

if [ -z "${LOCAL_ARTIFACTS}" ]; then
    curl -sfL -R -o artifacts/installer.sh https://raw.githubusercontent.com/k3s-io/k3s/master/install.sh
    chmod +x artifacts/installer.sh
    pushd artifacts
    if [ "${ARCH}" = "amd64" ]; then
        curl -sfL -R -o k3s https://github.com/k3s-io/k3s/releases/download/${URI_VERSION}/k3s
    else
        curl -sfL -R -o k3s https://github.com/k3s-io/k3s/releases/download/${URI_VERSION}/k3s-${ARCH}
    fi
    popd
else
    cp local/* artifacts
    chmod +x artifacts/installer.sh
fi
