#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p artifacts

if [[ -z "${LOCAL_ARTIFACTS}" ]]; then
    curl -sfL -R -o artifacts/installer.sh https://raw.githubusercontent.com/k3s-io/k3s/master/install.sh
    chmod +x artifacts/installer.sh

    if [[ "${ARCH}" = "s390x" ]] && [[ "${VERSION}" =~ ^v1\.(20|21)\. ]]; then
        echo "Skipping s390x - not supported for this version."
        exit
    fi

    if [[ "${ARCH}" = "amd64" ]]; then
        SUFFIX=""
    elif [[ "${ARCH}" = "arm" ]]; then
        SUFFIX="-${ARCH}hf"
    else
        SUFFIX="-${ARCH}"
    fi
    curl -sfL -R -o artifacts/k3s https://github.com/k3s-io/k3s/releases/download/${URI_VERSION}/k3s${SUFFIX}
else
    cp local/* artifacts
    chmod +x artifacts/installer.sh
fi
