#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

DOCKERFILE=package/Dockerfile

docker image build -f ${DOCKERFILE} -t ${IMAGE}-${OS}-${ARCH} .

echo Built ${IMAGE}-${OS}-${ARCH}
