#!/usr/bin/env bash
set -eox pipefail

cd $(dirname $0)/..

export DOCKER_CLI_EXPERIMENTAL=enabled

source ./scripts/version

echo "Creating and pushing manifest for: ${IMAGE}"

docker buildx imagetools create \
  --tag "${IMAGE}" \
  "${IMAGE}-linux-amd64" \
  "${IMAGE}-linux-arm64"

if [[ -n "${IID_FILE}" ]]; then
    docker buildx imagetools inspect "${IMAGE}"
fi
